---
- name: "Installing Pip3.9"
  hosts: local
  connection: local 
  become: yes
  tasks:
  - name: "Install Pip3.9"
    ansible.builtin.pip:
      name: netaddr
      state: present
      executable: pip3.9
  - name: "Install Boto3 botocore"
    ansible.builtin.pip:
        name:
          - boto3
          - botocore
        state: present