---
- name: "Creating ec2 and updating route53 record"
  hosts: local
  connection: local
  vars:
    ami_id: "ami-09c813fb71547fc4f"
    sg_id: "sg-01f9169658e1539df"
    hosted_zone_id: "Z06921933AGUP8YGI3FIB"
    domain_name: "devops-phani.fun"
  tasks:
    - name: "amazon.aws.ec2_instance module – Create & manage EC2 instances"
      amazon.aws.ec2_instance:
        name: "my-ec2-instance"
        instance_type: t3.micro
        image_id: ami_id

    - name: "Printing the details"
      ansible.builtin.debug:
        msg: "image id:: {{ ami_id }}"
